function LevelTileComponentTool::onActivated(%this)
{
    EWTreeWindow.hidden = true;
	
	%LevelTileCompTool = new GuiWindowCollapseCtrl() 
    {
      CollapseGroup = "-1";
      CollapseGroupNum = "-1";
      resizeWidth = "1";
      resizeHeight = "1";
      canMove = "1";
      canClose = "0";
      canMinimize = "0";
      canMaximize = "0";
      minSize = "50 50";
      EdgeSnap = "1";
      text = "Forest Editor";
      Margin = "0 0 0 0";
      Padding = "0 0 0 0";
      AnchorTop = "1";
      AnchorBottom = "0";
      AnchorLeft = "1";
      AnchorRight = "0";
      isContainer = "1";
      Profile = "ToolsGuiWindowCollapseProfile";
      HorizSizing = "windowRelative";
      VertSizing = "windowRelative";
      Position = EWTreeWindow.position;
      Extent = EWTreeWindow.extent;
      MinExtent = "210 100";
      canSave = "1";
      Visible = "1";
      tooltipprofile = "ToolsGuiToolTipProfile";
      hovertime = "1000";
      internalName = "PalleteWindow";
      canSaveDynamicFields = "0";

      new GuiTabBookCtrl() {
         TabPosition = "Top";
         TabMargin = "10";
         MinTabWidth = "60";
         TabHeight = "20";
         AllowReorder = "0";
         FrontTabPadding = "0";
         Docking = "Client";
         Margin = "3 1 3 3";
         Padding = "0 0 0 0";
         AnchorTop = "1";
         AnchorBottom = "0";
         AnchorLeft = "1";
         AnchorRight = "0";
         isContainer = "1";
         Profile = "ToolsGuiTabBookProfile";
         HorizSizing = "width";
         VertSizing = "height";
         position = "3 44";
         Extent = "210 205";
         MinExtent = "8 2";
         canSave = "1";
         Visible = "1";
         tooltipprofile = "ToolsGuiToolTipProfile";
         hovertime = "1000";
         canSaveDynamicFields = "0";
		 internalName = "LevelTileComponentToolTabBook";

         new GuiTabPageCtrl() {
            fitBook = "0";
            text = "Brushes";
            maxLength = "1024";
            Docking = "Client";
            Margin = "-1 0 0 0";
            Padding = "0 0 0 0";
            AnchorTop = "1";
            AnchorBottom = "0";
            AnchorLeft = "1";
            AnchorRight = "0";
            isContainer = "1";
            Profile = "ToolsGuiTabPageProfile";
            HorizSizing = "right";
            VertSizing = "bottom";
            position = "0 22";
            Extent = "210 194";
            MinExtent = "8 2";
            canSave = "1";
            Visible = "0";
            tooltipprofile = "ToolsGuiToolTipProfile";
            hovertime = "1000";
            internalName = "BrushesTab";
            canSaveDynamicFields = "0";

            new GuiScrollCtrl() {
               willFirstRespond = "1";
               hScrollBar = "alwaysOff";
               vScrollBar = "dynamic";
               lockHorizScroll = true;
               lockVertScroll = "0";
               constantThumbHeight = "0";
               childMargin = "0 0";
               mouseWheelScrollSpeed = "-1";
               Docking = "Client";
               Margin = "0 0 0 0";
               Padding = "0 0 0 0";
               AnchorTop = "1";
               AnchorBottom = "0";
               AnchorLeft = "1";
               AnchorRight = "0";
               isContainer = "1";
               Profile = "ToolsGuiScrollProfile";
               HorizSizing = "right";
               VertSizing = "bottom";
               position = "0 0";
               Extent = "210 194";
               MinExtent = "8 2";
               canSave = "1";
               Visible = "1";
               tooltipprofile = "ToolsGuiToolTipProfile";
               hovertime = "1000";
               canSaveDynamicFields = "0";

               new GuiTreeViewCtrl() {
                  tabSize = "16";
                  textOffset = "2";
                  fullRowSelect = "0";
                  itemHeight = "21";
                  destroyTreeOnSleep = "1";
                  MouseDragging = "1";
                  MultipleSelections = "1";
                  DeleteObjectAllowed = "1";
                  DragToItemAllowed = "1";
                  ClearAllOnSingleSelection = "1";
                  showRoot = "0";
                  internalNamesOnly = "1";
                  objectNamesOnly = "0";
                  useInspectorTooltips = "0";
                  tooltipOnWidthOnly = "0";
                  compareToObjectID = "1";
                  canRenameObjects = "1";
                  renameInternal = "1";
                  isContainer = "1";
                  Profile = "ToolsGuiTreeViewProfile";
                  HorizSizing = "right";
                  VertSizing = "bottom";
                  position = "1 1";
                  Extent = "208 2";
                  MinExtent = "8 2";
                  canSave = "1";
                  Visible = "1";
                  tooltipprofile = "ToolsGuiToolTipProfile";
                  hovertime = "1000";
                  canSaveDynamicFields = "0";
				  internalName = "LevelTileComponentToolBrushTree";
               };
            };
         };
         new GuiTabPageCtrl() {
            fitBook = "0";
            text = "Meshes";
            maxLength = "1024";
            Docking = "Client";
            Margin = "-1 0 0 0";
            Padding = "0 0 0 0";
            AnchorTop = "1";
            AnchorBottom = "0";
            AnchorLeft = "1";
            AnchorRight = "0";
            isContainer = "1";
            Profile = "ToolsGuiTabPageProfile";
            HorizSizing = "right";
            VertSizing = "bottom";
            position = "0 22";
            Extent = "210 183";
            MinExtent = "8 2";
            canSave = "1";
            Visible = "1";
            tooltipprofile = "ToolsGuiToolTipProfile";
            hovertime = "1000";
            internalName = "MeshesTab";
            canSaveDynamicFields = "0";

            new GuiScrollCtrl() {
               willFirstRespond = "1";
               hScrollBar = "alwaysOff";
               vScrollBar = "dynamic";
               lockHorizScroll = true;
               lockVertScroll = "0";
               constantThumbHeight = "0";
               childMargin = "0 0";
               mouseWheelScrollSpeed = "-1";
               Docking = "Client";
               Margin = "0 0 0 0";
               Padding = "0 0 0 0";
               AnchorTop = "1";
               AnchorBottom = "0";
               AnchorLeft = "1";
               AnchorRight = "0";
               isContainer = "1";
               Profile = "ToolsGuiScrollProfile";
               HorizSizing = "right";
               VertSizing = "bottom";
               position = "0 0";
               Extent = "210 194";
               MinExtent = "8 2";
               canSave = "1";
               Visible = "1";
               tooltipprofile = "ToolsGuiToolTipProfile";
               hovertime = "1000";
               canSaveDynamicFields = "0";

               new GuiTreeViewCtrl() {
                  tabSize = "16";
                  textOffset = "2";
                  fullRowSelect = "0";
                  itemHeight = "21";
                  destroyTreeOnSleep = "1";
                  MouseDragging = "0";
                  MultipleSelections = "0";
                  DeleteObjectAllowed = "0";
                  DragToItemAllowed = "0";
                  ClearAllOnSingleSelection = "1";
                  showRoot = "0";
                  internalNamesOnly = "0";
                  objectNamesOnly = "1";
                  useInspectorTooltips = "0";
                  tooltipOnWidthOnly = "0";
                  compareToObjectID = "1";
                  canRenameObjects = "1";
                  renameInternal = "0";
                  isContainer = "1";
                  Profile = "ToolsGuiTreeViewProfile";
                  HorizSizing = "right";
                  VertSizing = "bottom";
                  position = "1 -67";
                  Extent = "208 2";
                  MinExtent = "8 2";
                  canSave = "1";
                  Visible = "1";
                  AltCommand = "$ThisControl.onDoubleClick();";
                  tooltipprofile = "ToolsGuiToolTipProfile";
                  hovertime = "1000";
                  canSaveDynamicFields = "0";
				  internalName = "LevelTileComponentToolMeshTree";
               };
            };
         };
      };
      new GuiStackControl() {
         StackingType = "Horizontal";
         HorizStacking = "Left to Right";
         VertStacking = "Top to Bottom";
         Padding = "3";
         DynamicSize = "1";
         ChangeChildSizeToFit = "0";
         ChangeChildPosition = "0";
         isContainer = "1";
         Profile = "ToolsGuiDefaultProfile";
         HorizSizing = "left";
         VertSizing = "bottom";
         position = "170 25";
         Extent = "35 17";
         MinExtent = "16 16";
         canSave = "1";
         Visible = "0";
         tooltipprofile = "ToolsGuiToolTipProfile";
         hovertime = "1000";
         internalName = "MeshButtonGroup";
         canSaveDynamicFields = "0";

         new GuiBitmapButtonCtrl() {
            bitmap = "tools/LevelTileComponentTool/images/new-mesh";
            groupNum = "-1";
            buttonType = "PushButton";
            useMouseEvents = "0";
            isContainer = "0";
            Profile = "ToolsGuiDefaultProfile";
            HorizSizing = "left";
            VertSizing = "bottom";
            position = "0 0";
            Extent = "16 16";
            MinExtent = "8 2";
            canSave = "1";
            Visible = "1";
            Command = "LevelTileComponentToolGui.newMesh();";
            tooltipprofile = "ToolsGuiToolTipProfile";
            ToolTip = "Add New Mesh";
            hovertime = "1000";
            canSaveDynamicFields = "0";
         };
         new GuiBitmapButtonCtrl() {
            bitmap = "tools/gui/images/delete";
            groupNum = "-1";
            buttonType = "PushButton";
            useMouseEvents = "0";
            isContainer = "0";
            Profile = "ToolsGuiDefaultProfile";
            HorizSizing = "left";
            VertSizing = "bottom";
            position = "19 0";
            Extent = "16 16";
            MinExtent = "8 2";
            canSave = "1";
            Visible = "1";
            Command = "LevelTileComponentToolGui.deleteMesh();";
            tooltip = "Delete Selected";
            tooltipprofile = "ToolsGuiToolTipProfile";
            hovertime = "1000";
            canSaveDynamicFields = "0";
         };
      };
      new GuiStackControl() {
         StackingType = "Horizontal";
         HorizStacking = "Left to Right";
         VertStacking = "Top to Bottom";
         Padding = "3";
         DynamicSize = "1";
         ChangeChildSizeToFit = "0";
         ChangeChildPosition = "0";
         isContainer = "1";
         Profile = "ToolsGuiDefaultProfile";
         HorizSizing = "left";
         VertSizing = "bottom";
         position = "151 25";
         Extent = "54 17";
         MinExtent = "16 16";
         canSave = "1";
         Visible = "1";
         tooltipprofile = "ToolsGuiToolTipProfile";
         hovertime = "1000";
         internalName = "BrushButtonGroup";
         canSaveDynamicFields = "0";

         new GuiBitmapButtonCtrl() {
            bitmap = "tools/LevelTileComponentTool/images/new-brush";
            groupNum = "-1";
            buttonType = "PushButton";
            useMouseEvents = "0";
            isContainer = "0";
            Profile = "ToolsGuiDefaultProfile";
            HorizSizing = "left";
            VertSizing = "bottom";
            position = "0 0";
            Extent = "16 16";
            MinExtent = "8 2";
            canSave = "1";
            Visible = "1";
            Command = "LevelTileComponentToolGui.newBrush();";
            tooltipprofile = "ToolsGuiToolTipProfile";
            ToolTip = "Add New Brush Group";
            hovertime = "1000";
            canSaveDynamicFields = "0";
         };
         new GuiBitmapButtonCtrl() {
            bitmap = "tools/LevelTileComponentTool/images/new-element";
            groupNum = "-1";
            buttonType = "PushButton";
            useMouseEvents = "0";
            isContainer = "0";
            Profile = "ToolsGuiDefaultProfile";
            HorizSizing = "left";
            VertSizing = "bottom";
            position = "19 0";
            Extent = "16 16";
            MinExtent = "8 2";
            canSave = "1";
            Visible = "1";
            Command = "LevelTileComponentToolGui.newElement();";
            tooltip = "Add New Brush Element";
            tooltipprofile = "ToolsGuiToolTipProfile";
            hovertime = "1000";
            canSaveDynamicFields = "0";
         };
         new GuiBitmapButtonCtrl() {
            bitmap = "tools/gui/images/delete";
            groupNum = "-1";
            buttonType = "PushButton";
            useMouseEvents = "0";
            isContainer = "0";
            Profile = "ToolsGuiDefaultProfile";
            HorizSizing = "left";
            VertSizing = "bottom";
            position = "38 0";
            Extent = "16 16";
            MinExtent = "8 2";
            canSave = "1";
            Visible = "1";
            Command = "LevelTileComponentToolGui.deleteBrushOrElement();";
            tooltip = "Delete Selected";
            tooltipprofile = "ToolsGuiToolTipProfile";
            hovertime = "1000";
            canSaveDynamicFields = "0";
         };
      };
   };

   %this.toolWindow = %LevelTileCompTool;
   EditorGui.add(%LevelTileCompTool);
}

function LevelTileComponentTool::onDeactivated(%this)
{
	EditorGui.remove(%this.toolWindow);
	
	EWTreeWindow.hidden = false;
	
	%this.toolWindow.delete();
}